### PR TITLE
String attributes

### LINKED ISSUE #58: Exporter does not accept non-string attributes
We've got the following error:
```
json: cannot unmarshal number into Go struct field slave.attributes of type string
```
From the given mesos agent attributes:
```
"attributes": {
    "cuda": 9.0,
    "dc": "xxxx",
    "domain": "xxxx",
    "region": "xxxx"
},
```

### LINKED ISSUE #60: Error on master
Hi,

I've got an issue with the exporter on my masters :

`Error decoding response body from http://xx.xx.xx.xx:5050/state: json: cannot unmarshal number into Go value of type string`

If I check the url, it rewrote it on http://xx.xx.xx.xx:5050/master/state

I work with Mesos 1.4.0

### PR DESCRIPTION
**Pull request by jkt628**
fixes #60 
fixes #58

### CODE REVIEW

File: master_state.go [hunk 1]
```diff
@@ -179,7 +180,7 @@ func newMasterStateCollector(httpClient *httpClient, slaveAttributeLabels []stri
 				for key, value := range s.Attributes {
 					normalisedLabel := normaliseLabel(key)
 					if stringInSlice(normalisedLabel, normalisedAttributeLabels) {
-						slaveAttributesExport[normalisedLabel] = value
+						slaveAttributesExport[normalisedLabel] = string(value)
```
Comment (brian-brazil) [inline master_state.go]: This will lead to double quotes being included in the value if it's a string, and ranges being represented however they are rendered in the original json. I think you should use an `interface{}` as the type and have handling for strings and floats. It's probably easiest to drop ranges for now.

Comment (jkt628) [reply master_state.go]: :+1:

**Comment by jkt628** [comment]
created a simple conversion function
